conf/urls.py
"""ayudapy URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

from conf import api_urls
from core import views as core_views
from org import views as org_views
from org.views import RestrictedView

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('jara/', admin.site.urls),
    # home
    path('', core_views.home, name='home'),
    path('dar', TemplateView.as_view(template_name="giver/info.html")),
    path('legal', TemplateView.as_view(template_name="footer/legal.html"), name='legal'),
    path('voluntario/legal', TemplateView.as_view(template_name="volunteer/info.html"), name='voluntariolegal'),
    path('preguntas_frecuentes', core_views.view_faq, name='general_faq'),
    path('contacto', TemplateView.as_view(template_name="footer/contact_us.html"), name='contact_us'),
    # help requests
    path('recibir', TemplateView.as_view(template_name="help_request/info.html")),
    path('solicitar', core_views.request_form, name="request-form"),
    path('pedidos/<int:id>', core_views.view_request, name='pedidos-detail'),
    path('pedidos_ciudad/<slug:city>', core_views.list_by_city, name='pedidos-by-city'),
    path('pedidos', core_views.list_requests),
    # donations
    path('ceder', org_views.donation_form, name="donation-form"),
    path('donar', RestrictedView.as_view()),
    path('donaciones', org_views.list_donation),
    path('donaciones_ciudad/<slug:city>', org_views.list_donation_by_city, name='donation-by-city'),
    path('donaciones/<int:id>', org_views.view_donation_center, name='donaciones-detail'),
    # volunteer
    path('voluntario', TemplateView.as_view(template_name="volunteer/form.html"), name='voluntario'),
    # stats
    path('stats', core_views.stats, name='stats'),
    # login/logout
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += api_urls.urlpatterns
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

org/models.py
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from simple_history.models import HistoricalRecords

from geopy.geocoders import Nominatim

DEP = (
    (0, "Asuncion"),
    (1, "Alto Paraguay"),
    (2, "Alto Paraná"),
    (3, "Amambay"),
    (4, "Boquerón"),
    (5, "Caaguazú"),
    (6, "Caazapá"),
    (7, "Canindeyú"),
    (8, "Central"),
    (9, "Concepción"),
    (10, "Cordillera"),
    (11, "Guairá"),
    (12, "Itapúa"),
    (13, "Misiones"),
    (14, "Ñeembucú"),
    (15, "Paraguarí"),
    (16, "Presidente Hayes"),
    (17, "San Pedro"),
)


class BaseResource(models.Model):
    location = models.PointField("Ubicación", srid=4326,)
    address = models.CharField(
        "Dirección",
        help_text="Dirección, ciudad, barrio, referencias, o cómo llegar",
        max_length=400,
        blank=False,
        null=True,
    )
    city = models.CharField(max_length=30, blank=True, default="", editable=False)
    city_code = models.CharField(max_length=30, blank=True, default="", editable=False)
    active = models.BooleanField(default=True, db_index=True)
    added = models.DateTimeField(
        "Agregado", auto_now_add=True, null=True, blank=True, db_index=True
    )
    history = HistoricalRecords(inherit=True)

    def _get_city(self):
        geolocator = Nominatim(user_agent="ayudapy")
        cordstr = "%s, %s" % self.location.coords[::-1]
        location = geolocator.reverse(cordstr, language="es")
        city = ""
        if location.raw.get("address"):
            if location.raw["address"].get("city"):
                city = location.raw["address"]["city"]
            elif location.raw["address"].get("town"):
                city = location.raw["address"]["town"]
            elif location.raw["address"].get("locality"):
                city = location.raw["address"]["locality"]
        return city

    def save(self):
        from unidecode import unidecode
        city = self._get_city()
        self.city = city
        self.city_code = unidecode(city).replace(" ", "_")
        self.phone = self.phone.replace(" ", "")
        return super().save()

    class Meta:
        abstract = True


# Organization represents ...


class Organization(models.Model):
    name = models.CharField("Nombre de la Organización", max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Organización"
        verbose_name = "Organizaciones"

# Donation Center represents an establishment where the user with needs could go to
# receive some help.


class DonationCenter(models.Model):
    name = models.CharField("Nombre del lugar", max_length=200)
    phone = models.CharField("Teléfono de contacto", max_length=30, blank=True, null=True)
    location = models.PointField("Ubicación", srid=4326,)
    address = models.CharField(
        "Dirección",
        help_text="Dirección, ciudad, barrio, referencias, o cómo llegar",
        max_length=400,
        blank=False,
        null=True,
    )
    city = models.CharField(max_length=30, blank=True, default="", editable=False)
    city_code = models.CharField(max_length=30, blank=True, default="", editable=False)
    active = models.BooleanField(default=True, db_index=True)
    added = models.DateTimeField(
        "Agregado", auto_now_add=True, null=True, blank=True, db_index=True
    )
    history = HistoricalRecords()

    # TODO - getCity() se utliza en HelpRequest y otros modelos. Se podria unificar
    def _get_city(self):
        geolocator = Nominatim(user_agent="ayudapy")
        cordstr = "%s, %s" % self.location.coords[::-1]
        location = geolocator.reverse(cordstr, language="es")
        city = ""
        if location.raw.get("address"):
            if location.raw["address"].get("city"):
                city = location.raw["address"]["city"]
            elif location.raw["address"].get("town"):
                city = location.raw["address"]["town"]
            elif location.raw["address"].get("locality"):
                city = location.raw["address"]["locality"]
        return city

    def save(self):
        from unidecode import unidecode

        city = self._get_city()
        self.city = city
        self.city_code = unidecode(city).replace(" ", "_")
        self.phone = self.phone.replace(" ", "")
        return super(DonationCenter, self).save()

    def __str__(self):
        return f"<Centro #{self.id} - {self.name}> - {self.city}"

    class Meta:
        verbose_name = "Centro de Donación"
        verbose_name_plural = "Centros de Donación"


# Profile a model to represents volunteers.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField("Nombre", max_length=200)
    phone = models.CharField("Teléfono de contacto", max_length=30)
    birth_date = models.DateField(null=True, blank=True)
    location = models.PointField("Ubicación", srid=4326,)
    department = models.PositiveSmallIntegerField(choices=DEP)
    address = models.CharField(
        "Dirección",
        help_text="Dirección, ciudad, barrio, referencias, o cómo llegar",
        max_length=400,
        blank=False,
        null=True,
    )
    city = models.CharField(max_length=30, blank=True, default="", editable=False)
    city_code = models.CharField(max_length=30, blank=True, default="", editable=False)
    active = models.BooleanField(default=True, db_index=True)
    added = models.DateTimeField(
        "Agregado", auto_now_add=True, null=True, blank=True, db_index=True
    )

    def _get_city(self):
        geolocator = Nominatim(user_agent="ayudapy")
        cordstr = "%s, %s" % self.location.coords[::-1]
        location = geolocator.reverse(cordstr, language="es")
        city = ""
        if location.raw.get("address"):
            if location.raw["address"].get("city"):
                city = location.raw["address"]["city"]
            elif location.raw["address"].get("town"):
                city = location.raw["address"]["town"]
            elif location.raw["address"].get("locality"):
                city = location.raw["address"]["locality"]
        return city

    def save(self, **kwargs):
        from unidecode import unidecode

        city = self._get_city()
        self.city = city
        self.city_code = unidecode(city).replace(" ", "_")
        return super(Profile, self).save()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Voluntario"


class Pool(BaseResource):
    name = models.CharField("Nombre y Apellido", max_length=200, help_text="Nombre de la persona encargada")
    phone = models.CharField("Teléfono de contacto", max_length=30)
    info = models.TextField("Información", help_text="Cantidad de litros o dimensiones, ¿es una piscina o un reservorio?, etc...", blank=True, null=True)

    def __str__(self):
        return f"<Piscina #{self.id} - {self.name}> - {self.city}"

templates/base.html
{% load static %}
{% load leaflet_tags %}
{% load pipeline %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} AyudaPy {% endblock %}</title>

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="{% block fb-url %} {{ request.build_absolute_uri }} {% endblock %}">
    <meta property="og:title" content="{% block fb-title %} AyudaPy {% endblock %}">
    <meta property="og:description" content="{% block fb-description %} {% trans "A tool to help people help" %} {% endblock %}">
    <meta property="og:image" content="https://{% block fb-image %}{{ request.get_host }}{% static '/img/logo.jpg' %}{% endblock %}">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">


    <link rel="icon" href="{% static "logo_ayudapy.svg" %}" type="image/svg" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-switch@2.0.0/dist/css/bulma-switch.min.css">
    <!-- <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script> -->
    <script src="/static/scripts/fontawesome-custom.js"></script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162827339-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-162827339-1');
    </script>

    <style>
        .center {
            display: flex;
            justify-content: center;
            align-items: center;
            text-align: center;
        }

        .Site {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        .Site-content {
            flex: 1;
        }

        footer {
            padding: 1rem 1rem 1rem !important;
        }

        .hero {
            padding-bottom: 1rem;
        }

        .leaflet-container {
            /* all maps */
            z-index: 1;
        }

        ::placeholder {
            color: grey !important;
            opacity: 0.3 !important;
            font-size: 0.8rem;
        }

        .cities-dropdown-wrapper {
            margin-bottom: 1em;
        }

        .cities-dropdown input::-webkit-calendar-picker-indicator {
            opacity: 0;
        }

        .cities-dropdown .select {
            width: 100%;
        }


        .table-paginator>.has-multiple-pages-true,
        .table-paginator>.has-next-true,
        .table-paginator>.has-prev-true {
            display: block;
        }

        .table-paginator>.has-multiple-pages-false,
        .table-paginator>.has-next-false,
        .table-paginator>.has-prev-false {
            display: none;
        }


        .loader-wrapper {
            position: absolute;
            top: 0;
            left: 0;
            height: 100%;
            width: 100%;
            background: transparent;
            opacity: 0;
            z-index: -1;
            transition: opacity .3s;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 10px;
        }

        .loader-wrapper.is-active {
            opacity: 1;
            z-index: 10;
        }

        .loader-wrapper>.loader {
            height: 100px;
            width: 100px;
            border-width: 5px;
        }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/@vizuaalog/bulmajs@0.10.3/dist/file.js" integrity="sha256-9BDCQ1iKLp8eEXxQD6U8StZ4V2On9KFEHDeHeXLZ/aE=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@vizuaalog/bulmajs@0.10.3/dist/modal.js" integrity="sha256-HDcVnTQ5+DdyigrR4Xge4rxqguBi19XI7vNDhTDr+hs=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/combine/npm/moment@2.24.0/min/moment.min.js,npm/moment@2.24.0/locale/es.js"></script>
    {% leaflet_js plugins="ALL" %}
    {% leaflet_css plugins="ALL" %}
    {% javascript 'leaflet-patch.js' %}
</head>

<body class="Site">
    <section class="is-fullwidth" style="background-color: #33CCCC; height: 10%;">
        <div class="column is-8-mobile is-offset-2-mobile is-4-tablet is-offset-4-tablet is-2-desktop is-offset-5-desktop ">
            <a href="/">
                <figure class="image is-16by1">
                    <img src="{% static "img/logo2.svg" %}">
                </figure>
            </a>
        </div>
        <!-- TODO - to improve styling LOGIN/LOGOUT buttons -->
        </div>
    </section>
    <main class="Site-content">
        <section class="section">
            <div class="container">
                {% block bread %}
                {% endblock bread %}
                {% block content %}
                {% endblock content %}
            </div>
        </section>
    </main>
    {% include 'footer/footer.html' %}
</body>

</html>

templates/disclaimer.html
<div class="columns center" style="margin-top: 20px;">
	<div
		class="column is-two-third-mobile is-half-tablet is-half-desktop is-half-widescreen is-half-fullhd regular-shadow hover-grow"
		style="background-color: #2979ff;"
	>
		<article class="media">
			<figure class="media-left">
				<p class="image is-96x96">
					<img src="../static/img/img_important.svg" />
				</p>
			</figure>
			<div class="media-content">
				<div class="content">
					<p class="title is-4 has-text-white" style="overflow: hidden;">Importante</p>
					<p class="bd-notification is-primary has-text-white has-text-left">
						Esta es una plataforma ciudadana que depende totalmente de la buena voluntad de la gente. No hay
						garantías de recibir ayuda sí o sí. La información que uno carga va a ser 100% de acceso
						público.
					</p>
					<p class="has-text-justified">
						<a href="/legal" class="has-text-white">Mas info acá</a>
					</p>
				</div>
			</div>
		</article>
	</div>
</div>

<div class="columns center" style="margin-top: 20px;">
	<div
		class="column is-two-third-mobile is-half-tablet is-half-desktop is-half-widescreen is-half-fullhd regular-shadow hover-grow"
		style="background-color: white;"
	>
		<article class="media animated fadeIn">
			<figure class="media-left">
				<p class="image is-96x96">
					<img src="../static/img/img_howitsworks.svg" />
				</p>
			</figure>
			<div class="media-content">
				<div class="content">
					<p class="title is-4 has-text-black" style="overflow: hidden;">Cómo funciona</p>
					<p class="bd-notification is-primary has-text-black has-text-left">
						Tenés que cargar tu datos: nombre, teléfono de contacto, ciudad, ubicación y qué necesitás.
						<b>Argentina por vos</b> te permite poder compartir tu pedido de ayuda para que más gente lo
						vea, así como ofrecer a la gente que quiere ayudar una interfaz para buscar a los que necesitan.
					</p>
				</div>
			</div>
		</article>
	</div>
</div>

templates/donation.html
{% extends 'base.html' %}

{% block title %} Donación #{{donation_center.id}} {% endblock %}

{% block fb-title %} Donación #{{donation_center.id}} - {{ donation_center.title}} {% endblock %}

{% load leaflet_tags %}
{% load static %}
{% load l10n %}
{% load humanize %}
{% block bread %}
<nav class="breadcrumb  has-arrow-separator" aria-label="breadcrumbs">
    <ul>
        <li>
            <a href="/">
                <span class="icon is-small">
                    <i class="fas fa-home" aria-hidden="true"></i>
                </span>
                <span>Inicio</span>
            </a>
        </li>
        <li><a href="/donar">Info donar</a></li>
        <li><a href="/donaciones">Centros de donación</a></li>
        <li class="is-active"><a href="#" aria-current="page">Centro de donación #{{donation_center.id}}</a></li>
    </ul>
</nav>
{% endblock bread %}
{% block content%}
<div class="columns is-centered">
    <div class="subtitle center is-3">
        <a class="has-text-primary" href="/donaciones/{{donation_center.id}}">Centro de donación #{{donation_center.id}}</a>
    </div>
</div>
<div class="columns is-centered">
    <div class="column is-four-fifths">

        <div class="card">
            <header class="card-header has-background-light is-light">
                <p class="card-header-title is-size-4">{{ donation_center.name}}</p>
            </header>
            <section class="card-content">
                <p class="has-text-right is-size-7" title="{{donation_center.added|naturaltime}}">
                    {{donation_center.added}}</p>
                <p class="is-size-5">{{donation_center.message|linebreaksbr}}</p>
                <hr>
                <p class="subtitle">Nombre:</p>
                <p class="title is-4">{{ donation_center.name}}</p>
                {% if donation_center.phone %}
                    <p class="subtitle">Contacto:</p>
                    <p class="title is-4">
                        <a href="tel:{{donation_center.phone}}">
                            <img src="data:image/jpeg;base64,{{phone_number_img}}">
                        </a>
{#                        &nbsp;#}
{#                        <a href="https://wa.me/{{ whatsapp }}" target="_blank"#}
{#                            class="button is-medium is-success is-outlined">#}
{#                            <span class="icon is-small">#}
{#                                <i class="fab fa-whatsapp"></i>#}
{#                            </span>#}
{#                            <span>Contactar vía WhatsApp</span>#}
{#                        </a>#}
                    </p>
                {% endif %}
                {% if donation_center.address %}
                <p class="subtitle">Dirección:</p>
                <p class="title is-4">{{donation_center.address}}</p>
                {% endif %}
                <p class="subtitle">Ciudad: </p>
                <p class="title is-4">
                    <a href="/donaciones_ciudad/{{donation_center.city_code}}">{{donation_center.city}}</a>
                </p>
                <p class="subtitle">Ubicación:
                    {% leaflet_map "main" callback="main_map_init" %}
                </p>
                <a href="https://www.google.com/maps/search/?api=1&query={{donation_center.location.y|unlocalize}},{{donation_center.location.x|unlocalize}}"
                    target="_blank">
                    <button class="button is-medium is-fullwidth is-link is-light">
                        <span class="icon is-medium">
                            <i class="fas fa-map-marker-alt"></i>
                        </span>
                        <span>Abrir en Google Maps</span>
                    </button>
                </a>

            </section>

        </div>

        {% comment %} <article class="tile is-child is-box">
            <p class="subtitle">{{donation_center.message|linebreaks}}</p>
            <hr>
            <p class="subtitle">Nombre:</p>
            <p class="title is-4">{{ donation_center.name}}</p>
            <p class="subtitle">Contacto:</p>
            <p class="title is-4"><a href="tel:{{donation_center.phone}}">{{donation_center.phone}}</p></a>
            {% if donation_center.address %}
            <p class="subtitle">Dirección:</p>
            <p class="title is-4">{{donation_center.address}}</p>
            {% endif %}
            <p class="subtitle">Ubicación:
                {% leaflet_map "main" callback="main_map_init" %}
            </p>
            <a href="https://www.google.com/maps/search/?api=1&query={{donation_center.location.y|unlocalize}},{{donation_center.location.x|unlocalize}}"
                target="_blank">
                <button class="button is-medium is-fullwidth is-link is-light">
                    <span class="icon is-medium">
                        <i class="fas fa-map-marker-alt"></i>
                    </span>
                    <span>Abrir en Google Maps</span>
                </button>
            </a>
        </article> {% endcomment %}
        <hr>
        <label class="label has-text-success">
            <span class="icon is-medium"><i class="fas fa-hand-point-down"></i></span>
            Podés compartir esta donación haciendo click en los botones
        </label>
        <div class="is-fullwidth">
            {% include 'includes/share_buttons_donation.html'%}
        </div>

        <script type="text/javascript">
            function main_map_init(map, options) {
                // Use Leaflet API here
                {% autoescape off %}
                var lon = {{ donation_center.location.x| unlocalize}};
                var lat = {{ donation_center.location.y| unlocalize }};
                data = {{ donation_center.location.geojson }}
                {% endautoescape %}
                // zoom to point & add it to map
                map.setView([lat, lon], 14);
                //L.marker([lat, lon]).addTo(map);
                L.geoJson(data).addTo(map)
            }
        </script>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html'%}
{% load i18n %}

{% block content %}
<div class="is-fullhd">
    {% if not perms.org.add_donationcenter %}
    <div class="columns is-centered">
        <div class="column is-3">
            <a href="/recibir">
                <article class="tile is-child notification has-text-centered" style="background-color: #ffb852; color: white;">
                    <p class="title is-4">{% trans "I need help!" %}</p>
                    <p class="subtitle is-size-7">{% trans "Post your request for people to see it" %}</p>
                </article>
            </a>
        </div>
        <div class="column is-3">
            <a href="/dar">
                <article class="tile is-child notification has-text-centered" style="background-color: #4cd36f; color: white;">
                    <p class="title is-4">{% trans "I want to help!" %}</p>
                    <p class="subtitle is-6 is-size-7">{% trans "Find someone close to you to help" %}</p>
                </article>
            </a>
        </div>
    </div>
    <div class="columns is-centered">
        <!--<div class="column is-3">
            <a href="/donaciones">
                <article class="tile is-child notification has-text-centered" style="background-color: #6e6bd1; color: white;">
                    <p class="title is-4">{% trans "Donation Centers!" %}</p>
                    <p class="subtitle is-6 is-size-7">{% trans "See what you can donate and where" %}</p>
                </article>
            </a>
        </div>
        <div class="column is-3">
            <a href="/voluntario/legal">
                <article class="tile is-child notification has-text-centered" style="background-color: #f95d82; color: white;">
                    <p class="title is-4">{% trans "I want to volunteer!" %}</p>
                    <p class="subtitle is-size-7">{% trans "Help us to help" %}</p>
                </article>
            </a>
        </div> -->
    </div>
    {% else %}
    <div class="columns is-centered">
        <div class="column is-4">
            <a href="/dar">
                <article class="tile is-child notification has-text-centered" style="background-color: #4cd36f; color: white;">
                    <p class="title is-4">{% trans "I want to help!" %}</p>
                    <p class="subtitle is-6 is-size-7">{% trans "Find someone close to you to help" %}</p>
                </article>
            </a>
        </div>
        <!-- <div class="column is-4">
            <a href="/donaciones">
                <article class="tile is-child notification has-text-centered" style="background-color: #6e6bd1; color: white;">
                    <p class="title is-4">{% trans "Donation Centers!" %}</p>
                    <p class="subtitle is-6 is-size-7">{% trans "See what you can donate and where" %}</p>
                </article>
            </a>
        </div>
        <div class="column is-4">
            <a href="/donar">
                <article class="tile is-child notification has-text-centered" style="background-color: #f95d82; color: white;">
                    <p class="title is-4">{% trans "Register a Center!" %}</p>
                    <p class="subtitle is-6 is-size-7">{% trans "Register a Donation Center" %}</p>
                </article>
            </a>
        </div> -->
    </div>
    {% endif %}
</div>

{% endblock %}

templates/info_donation.html
{% extends 'base.html' %}
{% block bread %}
  <nav class="breadcrumb  has-arrow-separator" aria-label="breadcrumbs">
    <ul>
        <li>
            <a href="/">
                <span class="icon is-small">
                    <i class="fas fa-home" aria-hidden="true"></i>
                </span>
                <span>Inicio</span>
            </a>
        </li>
        <li class="is-active">
            <a href="#" aria-current="page">Info donar</a></li>
        </ul>
    </nav>
{% endblock bread %}
{% block content%}

<div class="columns is-centered center">
  <div class="column">
    <div class="tile is-ancestor center">
        <div class="tile is-5 is-vertical is-parent">
            <div class="tile is-child notification is-danger">
                <p class="title">Importante</p>
                <p class="has-text-justified">Esta es una plataforma ciudadana que depende totalmente de la buena voluntad de la gente. No hay garantías de recibir ayuda sí o sí.
            La información que uno carga va a ser 100% de acceso público.</p> <a href="/legal">Más info acá</a>
            </div>
            <div class="tile is-child is-warning box">
                <p class="title">¿Cómo funciona?</p>
                <p class="has-text-justified">Tenés que cargar tu datos: nombre, teléfono de contacto, ciudad, ubicación y qué necesitás.</p>
                <p class="has-text-justified"><b>AyudaPy</b> te permite poder compartir tu pedido de ayuda para que más gente lo vea, así como ofrecer a la gente que quiere ayudar una interfaz para buscar a los que necesitan</p>
            </div>
            <div class="tile is-child">
                <a href="/ceder">
                    <button class="button is-success is-large is-fullwidth is-size-5 has-text-weight-bold">
                    <span>OK entiendo, quiero continuar </span>
                    <span class="icon is-medium"><i class="fas fa-thumbs-up is-le"></i></span>
                    </button>
                </a>
            </div>
        </div>
    </div>
  </div>
</div>

{% endblock %}

templates/voluntary_form.html
{% extends 'base.html' %}
{% block bread %}
<nav class="breadcrumb  has-arrow-separator" aria-label="breadcrumbs">
  <ul>
    <li>
      <span class="icon is-small">
        <i class="fas fa-home" aria-hidden="true"></i>
      </span>
      <a href="/">Inicio</a></li>
    <li class="is-active"><a href="#" aria-current="page">Quiero ser voluntario</a></li>
  </ul>
</nav>
{% endblock bread %}
{% block content%}

<div class="columns is-centered center">
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdlQHsanu2HvAHz0FIwO_CnRCnQlRd3j0KriwAMNLJtGZQkBw/viewform?embedded=true" width="640" height="2220" frameborder="0" marginheight="0" marginwidth="0">Cargando…</iframe>

</div>

{% endblock %}